

export class RecursoNaoEncontradoErro extends Error {
    constructor(){
        super("Recurso n√£o encontrado")
    }
}